# 16 quiz Shorts. Country editions lead, because that was the measured
# differentiator: the 672-sub channel that hit 271k ran "TURKEY Edition" and
# "ENGLAND Edition" while generic quizzes sat at a ~1,100-view median.
#
# EVERY FACT NEEDS VERIFYING BEFORE POSTING. Knowledge cutoff is May 2026 and a
# World Cup ran that June-July, so anything all-time may be a tournament stale.
# `verify` marks how exposed each one is.

QUESTIONS = [
 # --- country editions (the angle that measurably works) ---
 dict(slug="eng_pl_scorers", country="ENGLAND",
      q=r"Can you name England's top 5\NPremier League goalscorers?",
      a=["Alan Shearer","Harry Kane","Wayne Rooney","Andy Cole","Frank Lampard"],
      s=["260","213","208","187","177"], verify="high — Kane's total moves"),
 dict(slug="bra_wc_scorers", country="BRAZIL",
      q=r"Can you name Brazil's top 5\NWorld Cup goalscorers?",
      a=["Ronaldo","Pelé","Jairzinho","Ademir","Vavá"],
      s=["15","12","9","9","9"], verify="HIGH — 2026 World Cup"),
 dict(slug="arg_caps", country="ARGENTINA",
      q=r"Can you name Argentina's top 5\Nmost-capped players?",
      a=["Lionel Messi","Javier Mascherano","Javier Zanetti","Roberto Ayala","Ángel Di María"],
      s=["190+","147","145","115","145"], verify="HIGH — Messi/Di María active"),
 dict(slug="ger_caps", country="GERMANY",
      q=r"Can you name Germany's top 5\Nmost-capped players?",
      a=["Lothar Matthäus","Miroslav Klose","Thomas Müller","Lukas Podolski","Bastian Schweinsteiger"],
      s=["150","137","130+","130","121"], verify="medium — Müller's total"),
 dict(slug="fra_scorers", country="FRANCE",
      q=r"Can you name France's top 5\Nall-time goalscorers?",
      a=["Olivier Giroud","Thierry Henry","Kylian Mbappé","Antoine Griezmann","Michel Platini"],
      s=["57","51","50+","44","41"], verify="HIGH — Mbappé active"),
 dict(slug="por_scorers", country="PORTUGAL",
      q=r"Can you name Portugal's top 5\Nall-time goalscorers?",
      a=["Cristiano Ronaldo","Pauleta","Eusébio","Luís Figo","Nuno Gomes"],
      s=["130+","47","41","32","29"], verify="HIGH — Ronaldo active"),
 dict(slug="ita_caps", country="ITALY",
      q=r"Can you name Italy's top 5\Nmost-capped players?",
      a=["Gianluigi Buffon","Fabio Cannavaro","Paolo Maldini","Daniele De Rossi","Andrea Pirlo"],
      s=["176","136","126","117","116"], verify="low — all retired"),
 dict(slug="ned_scorers", country="NETHERLANDS",
      q=r"Can you name the Netherlands'\Ntop 5 all-time goalscorers?",
      a=["Robin van Persie","Klaas-Jan Huntelaar","Patrick Kluivert","Memphis Depay","Dennis Bergkamp"],
      s=["50","42","40","45+","37"], verify="HIGH — Depay active"),
 dict(slug="esp_caps", country="SPAIN",
      q=r"Can you name Spain's top 5\Nmost-capped players?",
      a=["Sergio Ramos","Iker Casillas","Sergio Busquets","Xavi","Andrés Iniesta"],
      s=["180","167","143","133","131"], verify="low — all retired"),
 dict(slug="tur_legends", country="TURKEY",
      q=r"Can you name Turkey's top 5\Nall-time goalscorers?",
      a=["Hakan Şükür","Burak Yılmaz","Tuncay Şanlı","Cenk Tosun","Lefter Küçükandonyadis"],
      s=["51","31","22","20","21"], verify="medium"),
 # --- club editions ---
 dict(slug="rm_scorers", country="REAL MADRID",
      q=r"Can you name Real Madrid's\Ntop 5 all-time goalscorers?",
      a=["Cristiano Ronaldo","Karim Benzema","Raúl","Alfredo Di Stéfano","Santillana"],
      s=["450","354","323","308","290"], verify="low — all departed"),
 dict(slug="lfc_scorers", country="LIVERPOOL",
      q=r"Can you name Liverpool's\Ntop 5 all-time goalscorers?",
      a=["Ian Rush","Roger Hunt","Gordon Hodgson","Billy Liddell","Mohamed Salah"],
      s=["346","285","241","228","240+"], verify="HIGH — Salah active"),
 dict(slug="mufc_scorers", country="MAN UNITED",
      q=r"Can you name Man United's\Ntop 5 all-time goalscorers?",
      a=["Wayne Rooney","Bobby Charlton","Denis Law","Jack Rowley","Dennis Viollet"],
      s=["253","249","237","211","179"], verify="low — all retired"),
 dict(slug="fcb_scorers", country="BARCELONA",
      q=r"Can you name Barcelona's\Ntop 5 all-time goalscorers?",
      a=["Lionel Messi","César Rodríguez","László Kubala","Luis Suárez","Samuel Eto'o"],
      s=["672","232","194","195","130"], verify="low — all departed"),
 # --- records ---
 dict(slug="ucl_clubs", country="CHAMPIONS LEAGUE",
      q=r"Can you name the 5 clubs with\Nthe most European Cups?",
      a=["Real Madrid","AC Milan","Bayern Munich","Liverpool","Barcelona"],
      s=["15","7","6","6","5"], verify="HIGH — 2026 final"),
 dict(slug="ballondor", country="BALLON D'OR",
      q=r"Can you name the 5 players with\Nthe most Ballon d'Ors?",
      a=["Lionel Messi","Cristiano Ronaldo","Michel Platini","Johan Cruyff","Marco van Basten"],
      s=["8","5","3","3","3"], verify="HIGH — 2025/26 awards"),
]
